import type { Metadata } from 'next'
import { Unbounded, Roboto, Roboto_Flex, Barriecito } from 'next/font/google'
import './globals.css'

const unbounded = Unbounded({
  variable: '--font-unbounded',
  subsets: ['latin'],
  display: 'swap',
  weight: ['900'],
})
const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
})
const barriecito = Barriecito({
  variable: '--font-barriecito',
  subsets: ['latin'],
  display: 'swap',
  weight: ['400'],
})
const robotoFlex = Roboto_Flex({
  variable: '--font-roboto-flex',
  subsets: ['latin'],
  display: 'swap',
  axes: ['wdth'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${unbounded.variable} ${roboto.variable} ${robotoFlex.variable} ${barriecito.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
